version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-mp-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: laravel-mp-nginx
    restart: unless-stopped
    ports:
      - "1002:80"  # port host 1002 → nginx 80
    volumes:
      - ./public:/var/www/public:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - laravel

networks:
  laravel:
    external:
      name: floratrade-eks_laravel  # network yang sama dengan EKS

